name: Packagist

on:
  push:
    branches: [main]
    tags: ['*']
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
          REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
        run: |
          curl -fsS -X POST -H 'Content-Type: application/json' \
              "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_TOKEN}" \
              -d "{\"repository\":{\"url\":\"${REPOSITORY_URL}\"}}"
